export type CatchGuide = {
  speciesId: string
  whereToFind: string[]
  bestBait: { name: string; when: string }[]
  technique: string[]
  bestTime: string
  proTips: string[]
}

export const CATCH_GUIDES: CatchGuide[] = [
  // ─── SALMON ──────────────────────────────────────────────────────────────────
  {
    speciesId: 'chinook',
    whereToFind: [
      'Deep holes and tailouts in the main river channel — Chinook hug the bottom',
      'Near river mouths and tidewater during August–September peak migration',
      'Side channels and slack water during high, turbid flows',
      'Below hatchery facilities where returning adults hold before spawning',
    ],
    bestBait: [
      { name: 'Cured salmon eggs', when: 'Best all-around bait; use in drift or float rigs year-round' },
      { name: 'Sand shrimp', when: 'Deadly in clear-to-medium water; whole or tail-hooked' },
      { name: 'Blue Fox / Mepps spinner #5–6', when: 'Effective for active fish in moderate current' },
      { name: 'Kwikfish / Flatfish plug', when: 'Top choice in high, discolored water — wrap with sardine for scent' },
      { name: 'Whole or cut herring', when: 'Saltwater trolling and river mouths during tidal influence' },
    ],
    technique: [
      'Back-bounce cured eggs through deep holes — keep bait ticking the bottom at 1–3 mph',
      'Drift fish with a float and jig or sand shrimp through tailouts and seams',
      'Back-troll plugs at slow speed (1–2 mph) in deep runs; bait-wrapped for extra attraction',
      'Plunk from bank with a heavy pyramid sinker and 18–24 inch leader in slower tidal water',
    ],
    bestTime: 'Early morning and late evening on an incoming tide at river mouths; peak run timing is July–September on most WA rivers.',
    proTips: [
      'Most WA rivers require hatchery-only (clipped adipose fin) — always check before keeping a fish',
      'Fish the seam between fast and slow water where Chinook stage waiting for the tide to push them upriver',
      'A fresh rain event brings new fish into the system — hit the river 1–2 days after a rise for the best action',
    ],
  },
  {
    speciesId: 'coho',
    whereToFind: [
      'Shallower runs and riffles than Chinook — coho are mid-column and aggressive chasers',
      'Pools behind log jams and woody debris in the lower and mid river',
      'Tidal estuaries and river mouths as fish stage before their upstream push',
      'Farther upriver than most salmon species — coho will push well into small tributaries',
    ],
    bestBait: [
      { name: 'Pink or red spinners', when: 'Top producer in rivers on fresh-run fish; swing across current' },
      { name: 'Cured eggs in coon shrimp skein', when: 'Deadly for dark water and late-season fish' },
      { name: 'Pink/chartreuse 1/2 oz jig', when: 'Excellent in slower pools and deeper runs' },
      { name: 'Small spoon (Pixee, Little Cleo)', when: 'Great for covering water and locating aggressive fish' },
      { name: 'Woolly bugger / coho fly', when: 'Fly fishing in clearer flows — stripped aggressively near surface' },
    ],
    technique: [
      'Swing spinners across-and-downstream through runs; pause and flutter at the end of the swing',
      'Dead-drift cured eggs under a float in slower tailouts and pool edges',
      'Jig fishing in deeper pools — hop the jig off the bottom with short sharp lifts',
      'Troll flasher + coho fly combo at 3–4 mph in salt water for pre-migratory fish',
    ],
    bestTime: 'September–November peak in rivers; fresh-run fish entering from salt are the most aggressive — hit tidewater first as runs begin.',
    proTips: [
      'Coho often roll and porpoise at the surface revealing their location — cast 10–15 feet ahead of rolling fish',
      'Chrome-bright, ocean-fresh fish fight hardest and taste best; darker fish near spawning are still catchable but decline in quality',
      'Overcast days consistently produce more coho than sunny bright days — plan your trips accordingly',
    ],
  },
  {
    speciesId: 'sockeye',
    whereToFind: [
      'Main river channel mid-depth where schooling fish stack in current seams',
      'Lake Wenatchee and Lake Chelan near inlet streams during July–August peak',
      'Below hatchery outlets and tributary confluences on the Skagit and Columbia',
      'Mid-river where fish school before pushing to lake spawning grounds',
    ],
    bestBait: [
      { name: 'Small fluorescent yarn (size 4–6 hook)', when: 'Sockeye are plankton feeders — yarn mimics egg clusters and draws strikes' },
      { name: 'Bare or beaded hook under float', when: 'Legal flossing setup where allowed; keep hook near bottom in current' },
      { name: 'Small spinner blade (hammered brass/chartreuse)', when: 'May trigger reaction strikes from fresh fish in clearer water' },
      { name: 'Small pink jig', when: 'Effective in slower pool edges when fish are stacked' },
    ],
    technique: [
      'Drift a long leader (4–6 ft) past schooling fish near the bottom — most sockeye are foul-hooked by mouth contact, not a traditional bite',
      'Float fishing with yarn and small hook in the current seam just above fish depth',
      'Keep presentations small and light — this is finesse fishing, not power fishing',
      'In lakes, troll small spinners or wedding ring combos at 1.5–2 mph near tributaries',
    ],
    bestTime: 'Early morning when fish are most active at the surface; July–August is peak season on most WA waters.',
    proTips: [
      'WA sockeye fisheries are often hatchery-only with adipose clip requirements — verify before your trip',
      'Check WDFW emergency closures before going: sockeye runs vary hugely year to year and closures happen with little notice',
      'Skagit sockeye have a very narrow window, often July only — watch WDFW announcements closely',
    ],
  },
  {
    speciesId: 'chum',
    whereToFind: [
      'Lower tidal river reaches — chum rarely travel far from saltwater',
      'Hood Canal tributaries: Skokomish, Deschutes, Hamma Hamma, and Dungeness rivers',
      'Tidewater pools and riffles in the lower mainstem near spawning gravel',
      'Beach and estuary areas in Hood Canal during the initial tidal push',
    ],
    bestBait: [
      { name: 'Chartreuse or pink yarn fly', when: 'The classic chum attractor — bright colors trigger aggressive strikes' },
      { name: 'Fluorescent pink/orange jig', when: 'Excellent in deeper runs and tidal pools' },
      { name: 'Pink spinner', when: 'For covering water and locating aggressive pods of fish' },
      { name: 'Marabou streamer (chartreuse/pink)', when: 'Fly fishing — chum will chase aggressively near spawning time' },
    ],
    technique: [
      'Swing bright flies and jigs through runs with an across-and-downstream presentation',
      'Use medium-heavy gear — chum are powerful fish that hit hard and run fast',
      'Fish near spawning gravel in lower river sections where fish congregate in groups',
      'Look for rolling or jumping fish to locate active pods before casting',
    ],
    bestTime: 'October–November; target bright chrome fish near tidewater for best fighting quality and table fare.',
    proTips: [
      'Chum are one of the most overlooked WA salmon but fight pound-for-pound harder than Chinook — give them a try',
      'Hood Canal runs are the most reliable in the state; the Skokomish and Deschutes have consistent access',
      'Meat quality drops quickly once fish color up (turn green/purple) — target chrome fish in tidal areas, not upriver',
    ],
  },
  {
    speciesId: 'pink',
    whereToFind: [
      'Lower river mainstems in large visible schools — pinks stack up near tidewater',
      'Puget Sound beaches and estuaries during even-year (2026, 2028) runs',
      'Very accessible from shore — look for fish leaping and rolling in shallow water',
      'Puyallup, White, Skagit, Nooksack, Snohomish rivers have massive odd-year runs',
    ],
    bestBait: [
      { name: 'Small pink spinner (1/4 oz)', when: 'The #1 pink salmon lure; cast across current and retrieve quickly' },
      { name: 'Chartreuse or pink jig', when: 'Excellent in pools and slower water; also effective for jack Chinook' },
      { name: 'Small pink spoon', when: 'Great for covering beach areas in salt water' },
      { name: 'Bare hook or yarn fly', when: 'When fish are thick and feeding aggressively — pinks bite almost anything' },
    ],
    technique: [
      'Cast across current and retrieve at a medium-fast pace — pinks are aggressive and will chase',
      'Light to medium gear (8–12 lb line) maximizes the fun — these fish jump repeatedly',
      'Fish beach areas of Puget Sound by wading and casting parallel to shore on an incoming tide',
      'In rivers, target the seam between fast and slow water where schools hold',
    ],
    bestTime: 'Late July through September in odd years (2025, 2027); incoming tide on beaches; early morning is most active.',
    proTips: [
      'Best bang-for-buck salmon in WA — most abundant, easiest to catch, and the limit is usually 6/day',
      'Pinks run on odd years in most WA systems — plan your trip calendar carefully',
      'Light tackle makes pink salmon much more fun; a 6–7 wt fly rod is ideal and they will absolutely smoke you',
    ],
  },
  {
    speciesId: 'kokanee',
    whereToFind: [
      'Open water in lakes at the thermocline depth (usually 20–50 feet in summer)',
      'Near inlet tributaries in summer and fall as fish prepare to spawn',
      'Lake Chelan, Lake Roosevelt, and Sullivan Lake are top WA kokanee destinations',
      'Schools visible on fish finders as tight horizontal bands at consistent depth',
    ],
    bestBait: [
      { name: 'Wedding ring spinner with white corn', when: 'Classic WA kokanee setup trolled at thermocline depth' },
      { name: 'Small Dick Nite spoon', when: 'Excellent when trolled at 1.5–2 mph with a dodger or flasher' },
      { name: 'Kokanee dodger + hoochie', when: 'Standard troll rig; use UV-reactive colors in deeper water' },
      { name: 'Small marabou jig', when: 'For jigging over schools located on the sonar' },
    ],
    technique: [
      'Troll at a slow, precise speed (1.5–2 mph) to match kokanee swimming speed',
      'Use a dodger 18–24 inches ahead of the lure for added flash and action',
      'Locate the thermocline with a fish finder and keep your lures at that depth',
      'Add scent (anise oil or shrimp brine) to lures for increased attraction',
    ],
    bestTime: 'Spring (May–June) when fish are shallower and more active; late summer as fish begin spawning migration.',
    proTips: [
      'Kokanee have very soft mouths — use light drag and keep steady pressure to avoid tearing the hook out',
      'White shoepeg corn on the hook tipped behind a wedding ring is the time-tested WA kokanee technique',
      'Check for legal angling restrictions near spawning tributary mouths in fall — some areas are closed to protect spawners',
    ],
  },
  // ─── TROUT ────────────────────────────────────────────────────────────────────
  {
    speciesId: 'steelhead',
    whereToFind: [
      'Tailouts of pools where the pool shallows and speeds up — the classic steelhead holding lie',
      'Boulder gardens with current breaks and pockets of slower water',
      'Slots and seams behind large boulders on the inside bend of river curves',
      'Deeper runs with 3–6 feet of water and moderate current on bright days',
    ],
    bestBait: [
      { name: 'Sand shrimp (whole or tail)', when: 'The #1 bait in WA — deadly in all conditions, especially stained water' },
      { name: 'Cured eggs / Corkies', when: 'Drift fishing standard; pink/orange in stained water, natural in clear' },
      { name: 'Jig under float (1/4–3/8 oz)', when: 'Most versatile presentation — covers pools and runs efficiently' },
      { name: 'Intruder fly / egg-sucking leech', when: 'Fly fishing classic; swing through runs on 2-handed Spey rod' },
      { name: 'Rubber worm (10 inch pink/purple)', when: 'Sleeper bait that works especially well in low clear water' },
    ],
    technique: [
      'Drift fish near the bottom — keep your rig ticking the gravel through the run at current speed',
      'Float/bobber fishing with jig or shrimp covering pool drop-offs and tail-outs',
      'Spey casting — swing flies through the run from top to bottom, covering all lanes systematically',
      'Side-drifting from a drift boat: anchor, drift, re-anchor — methodically cover productive stretches',
    ],
    bestTime: 'Winter runs December–March; summer runs June–September (different rivers — check WDFW); overcast days and slightly stained water produce best.',
    proTips: [
      'Most WA steelhead rivers require barbless hooks — crimp your barbs before you leave the truck',
      'Wild steelhead must be released on most WA rivers — check for an intact adipose fin before putting fish in the cooler',
      'The Hoh, Sol Duc, Skagit, and Skykomish are world-class systems; fish get lockjaw in bright midday sun — focus on low-light periods',
    ],
  },
  {
    speciesId: 'rainbow',
    whereToFind: [
      'Riffles with oxygenated water — rainbows prefer well-oxygenated current edges',
      'Behind boulders, root wads, and logs where trout wait for drifting food',
      'Undercut banks offering overhead cover and ambush positions',
      'Deeper pools during warm summer months when surface water temperature rises',
    ],
    bestBait: [
      { name: 'PowerBait (stocked fish)', when: 'Top bait for recently stocked lakes; use floating formula on a small hook' },
      { name: 'Night crawlers / red worms', when: 'Universal natural bait; float under a small bobber or drift in current' },
      { name: 'Panther Martin / Rooster Tail spinner', when: 'Best searching lure for covering water in streams' },
      { name: 'Salmon eggs (single egg)', when: 'Small streams and clear water — natural and effective year-round' },
      { name: 'Dry fly (elk hair caddis, parachute adams)', when: 'Summer evenings when fish are rising to surface insects' },
    ],
    technique: [
      'Float fishing with bait: set a small bobber 18–36 inches above the bait and drift along current seams',
      'Drift fishing in rivers: cast upstream and follow the line downstream at current speed for a natural drift',
      'Spin cast small lures across the current and retrieve at medium speed through likely holding water',
      'Fly fishing: cast upstream with dry flies during hatches, nymph fish deeper runs with split shot',
    ],
    bestTime: 'Spring and fall are prime; early morning and evening are consistently best; avoid mid-day summer heat when trout go deep.',
    proTips: [
      'Stocked fish stack near hatchery truck access points early in the season — look for them in the first few hundred yards of a lake or river',
      'Wild fish are easily spooked — approach slowly, kneel on the bank, and fish upstream to stay behind the fish',
      'Match the insect hatch when fly fishing — observe what bugs are present and choose your fly accordingly',
    ],
  },
  {
    speciesId: 'cutthroat',
    whereToFind: [
      'Sea-run cutthroat patrol estuaries and river mouths in shallow water — very different from resident fish',
      'Resident cutthroat hold near banks and shallow margins, unlike rainbow which prefer mid-current',
      'Smaller streams and headwater tributaries for native resident fish',
      'Below waterfalls and natural barriers that define the upper limits of sea-run fish',
    ],
    bestBait: [
      { name: 'Small spinners (Worden\'s Rooster Tail)', when: 'Excellent in streams year-round for both sea-run and resident fish' },
      { name: 'Woolly bugger (olive/black)', when: 'Fly classic — strip near the bottom in estuary channels and river mouths' },
      { name: 'Sculpin pattern flies', when: 'Large streamers for trophy fish in larger rivers' },
      { name: 'Herring strip / small spoon', when: 'Sea-run fish in estuaries and Puget Sound beach areas' },
    ],
    technique: [
      'Strip streamers through estuaries with an irregular retrieve — pause, twitch, pull',
      'Swing wet flies downstream through pools and runs; let the fly hang in the current at the end of the swing',
      'Use light tackle (4–6 lb line) for maximum sport on smaller streams',
      'Wade quietly and work upstream — cutthroat are easily spooked from above',
    ],
    bestTime: 'Sea-run: August–November as they enter freshwater; resident fish year-round with spring being peak for aggressive feeding.',
    proTips: [
      'Sea-run cutthroat are one of WA\'s most underrated fisheries — many rivers are open and lightly pressured',
      'Identify by the distinctive red or orange slash marks under each side of the jaw — don\'t confuse with rainbow',
      'Most WA rivers require barbless hooks for cutthroat; gentle catch-and-release preserves these wild fish',
    ],
  },
  {
    speciesId: 'bull',
    whereToFind: [
      'Cold, clean headwater streams with deep pools and large boulders for cover',
      'Confluences where cold tributaries flow into larger rivers — bull trout seek cold water year-round',
      'Deep pools below log jams and in the shadow of steep canyon walls',
      'High-elevation lakes connected to cold stream systems in the Cascades',
    ],
    bestBait: [
      { name: 'Large streamer flies (sculpin, leech)', when: 'Bull trout are piscivores — big presentations trigger strikes' },
      { name: 'Large spinner (Mepps #4–5 blade)', when: 'Covers water effectively in deeper runs and pools' },
      { name: 'Spoon (Thomas Buoyant, Kastmaster)', when: 'Flash and action works well in deeper pools' },
      { name: 'Artificial only — check regs', when: 'Many WA bull trout waters are artificial-only, barbless hook required' },
    ],
    technique: [
      'Cast large streamers across current and strip with irregular pauses — bull trout ambush from behind cover',
      'Work deep pools slowly — bull trout are ambush predators that don\'t chase far',
      'Drift spinners along the bottom near large boulders and root wads',
      'Fish during early morning when water is coldest and fish are most active',
    ],
    bestTime: 'Summer (July–September) in cold headwaters; early morning when water temperatures are lowest.',
    proTips: [
      'Bull trout are a threatened species — catch-and-release only on almost all WA waters; handle gently in cold water',
      'Check regulations carefully before targeting — many waters are closed or heavily restricted for bull trout',
      'Bull trout require extremely cold, clean water; their presence indicates a high-quality, pristine stream ecosystem',
    ],
  },
  {
    speciesId: 'brook',
    whereToFind: [
      'High-elevation lakes in the Cascades and Olympics where they were widely planted',
      'Small headwater streams with cold, clear water and abundant insect life',
      'Undercut banks and spring seeps in smaller streams where cold groundwater enters',
      'Mountain lakes above 3,000 feet — brook trout dominate many WA alpine lakes',
    ],
    bestBait: [
      { name: 'Small spinners (size 0–2)', when: 'Best covering lure for alpine lakes; cast to cruising fish near shore' },
      { name: 'Small dry flies / elk hair caddis', when: 'Summer afternoons when brookies rise aggressively to the surface' },
      { name: 'Small spoons (1/8 oz)', when: 'Good flash action for lake fishing' },
      { name: 'Worm under float', when: 'Simple and effective; brookies are not selective about bait' },
    ],
    technique: [
      'Alpine lake fishing: fan cast from shore covering different depths until you locate fish',
      'Fly fishing: brookies rise freely to dry flies — light tippet and small flies in size 14–18',
      'Still water: use a slow, irregular retrieve to mimic wounded baitfish or large insects',
      'Stream fishing: present upstream and dead-drift through likely holding water',
    ],
    bestTime: 'June–August in mountain lakes after ice-out; evenings when fish are most active near the surface.',
    proTips: [
      'Brook trout are aggressive and easy to catch — perfect for beginners and family trips to mountain lakes',
      'No minimum size on many WA brook trout waters — check local regs, but limits are often generous',
      'In some eastern WA waters, brook trout are considered invasive and removal is encouraged',
    ],
  },
  {
    speciesId: 'brown',
    whereToFind: [
      'Deeper, slower pools in tailwaters below reservoirs — browns favor different water than rainbows',
      'Undercut banks with overhead cover; browns are notoriously shy and secretive',
      'Spring creek habitats with consistent cold temperatures and good insect life',
      'The Yakima River and a few eastern WA tailwaters hold quality brown trout populations',
    ],
    bestBait: [
      { name: 'Large streamer (Muddler Minnow, Woolly Bugger)', when: 'Trophy browns chase big meals — especially early morning and after dark' },
      { name: 'Rapala Original Floating (size 9–11)', when: 'Classic trophy brown lure; twitch and pause near banks' },
      { name: 'Night crawlers (large)', when: 'Evening and after-dark fishing for bigger fish' },
      { name: 'Dry flies (size 16–20 emergers)', when: 'Selective browns during heavy insect hatches' },
    ],
    technique: [
      'Fish at dusk and into dark for the biggest brown trout — they become much more active in low light',
      'Long leaders (9–12 ft) and delicate presentations are necessary for educated fish',
      'Work large streamers with a cross-stream swing and aggressive strips for trophy fish',
      'Approach with extreme caution — brown trout are the wariest freshwater fish in WA',
    ],
    bestTime: 'Fall spawning period (October–November) when males become aggressive; dusk and dawn year-round.',
    proTips: [
      'Brown trout are the hardest WA trout to catch — their wariness makes them a prestige target for skilled anglers',
      'Fish after midnight for the true trophies; big browns are almost exclusively nocturnal predators',
      'The Yakima River is WA\'s best brown trout fishery — dry fly fishing there is world-class in summer',
    ],
  },
  {
    speciesId: 'lake-trout',
    whereToFind: [
      'Deep, cold water — 50–150 feet in summer; shallower in spring and fall',
      'Rocky points and ledges at depth transitions in large eastern WA lakes',
      'Lake Roosevelt (the Columbia River reservoir) has the best WA lake trout fishing',
      'Near the thermocline in summer, chasing forage fish schools',
    ],
    bestBait: [
      { name: 'Large tube jig (2–4 oz) with minnow', when: 'Vertical jigging from a boat over deep structure is the most effective technique' },
      { name: 'Spoon (Swedish Pimple, Krocodile)', when: 'Drop to depth and work with aggressive lift-drop jigging action' },
      { name: 'Deep trolling with large streamer/spoon', when: 'Cover more water; run lures at 50–120 foot depth' },
      { name: 'Live or cut whitefish/sucker', when: 'Spring and fall when lake trout are in shallower water' },
    ],
    technique: [
      'Vertical jigging: drop lure to bottom, raise 2–4 feet and snap jig upward, let it flutter back down',
      'Deep trolling with downriggers at the depth fish are located on the sonar',
      'Use a fish finder to locate schools of forage fish — lake trout will be just below them',
      'Spring ice-out: fish rocky shorelines at 15–30 feet when lake trout are most accessible',
    ],
    bestTime: 'Spring (April–May) and fall (October–November) when fish move shallow; early morning on calm days.',
    proTips: [
      'Lake trout require a dedicated deep-water boat setup — hand-lining or heavy jigging gear is standard',
      'They\'re slow growing and relatively rare in WA — consider releasing larger fish as they\'re the breeders',
      'Lake Roosevelt is best accessed from Kettle Falls or Northport on the Canadian border area',
    ],
  },
  {
    speciesId: 'whitefish',
    whereToFind: [
      'Clean, cold rivers with gravel and rock bottoms — especially clear eastern Cascade rivers',
      'Deep slow pools and eddies in larger rivers during winter months',
      'The Methow, Wenatchee, and Yakima rivers have excellent whitefish populations',
      'Below riffles where they feed on drifting invertebrates throughout the water column',
    ],
    bestBait: [
      { name: 'Small nymph (hare\'s ear, pheasant tail size 14–18)', when: 'Top fly fishing bait drifted near the bottom' },
      { name: 'Maggots / waxworms', when: 'Excellent bait especially during winter ice fishing on eastern WA lakes' },
      { name: 'Small wet fly (size 12–16)', when: 'Swing through pools; whitefish will rise to the surface readily' },
      { name: 'Small spin lure (size 0–1 spinner)', when: 'For covering riffles and runs systematically' },
    ],
    technique: [
      'Nymph fishing with an indicator is the most consistent technique — present near the bottom in current',
      'Whitefish will rise to dry flies in summer — small dry fly presentations work well',
      'Ice fishing in winter: drop maggots or small jigs through the ice to suspended schools',
      'Use lighter, more finesse-oriented gear than you\'d use for trout — 4–6 wt fly rod or ultralight spinning',
    ],
    bestTime: 'Winter peak (December–February) when spawning fish are most abundant and concentrated in rivers.',
    proTips: [
      'Mountain whitefish are an underrated sport fish — they fight hard on light tackle and are excellent table fare',
      'Their small mouth requires smaller hook sizes than most people use; size 12–18 is standard',
      'No size limit or very liberal limits on most WA rivers — a great winter option when other species are closed',
    ],
  },
  // ─── BASS / WARMWATER ────────────────────────────────────────────────────────
  {
    speciesId: 'largemouth',
    whereToFind: [
      'Weed beds, lily pads, and submerged aquatic vegetation in shallow water (2–8 feet)',
      'Submerged timber, dock pilings, and woody structure along lake margins',
      'Rocky points and gravel humps during the spring spawn',
      'Lake Sammamish, Lake Washington, Banks Lake, and Columbia River backwaters are top WA waters',
    ],
    bestBait: [
      { name: 'Texas-rigged plastic worm (6–10 inch)', when: 'Year-round producer; green pumpkin and watermelon are top WA colors' },
      { name: 'Topwater frog over weeds', when: 'Summer mornings over lily pads and thick mats — violent explosive strikes' },
      { name: 'Swim jig with trailer', when: 'Working weed edges and along deeper structure' },
      { name: 'Spinnerbait (white or chartreuse)', when: 'Searching lure for covering water; works well in stained water' },
      { name: 'Drop shot (finesse worm 4–6 inch)', when: 'When fish are pressured or post-cold-front lethargic' },
    ],
    technique: [
      'Pitch plastic worms and jigs into tight cover — docks, brush piles, lily pad edges; let bait sink before slowly lifting',
      'Walk topwater frogs over surface mats in low light; delay your hookset until you feel the weight of the fish',
      'Slow-roll spinnerbait along weed lines at various depths to find active fish',
      'During spawn (May–June): sight fish on beds in 2–6 feet; use slow, subtle presentations',
    ],
    bestTime: 'Spring spawning season (May–June) when bass are in shallow water and highly aggressive; early morning and evening year-round.',
    proTips: [
      'During the spawn bass protect their beds aggressively — look for light-colored circular patches on gravel bottom',
      'Post-spawn fish go deep and are harder to catch — switch to deeper structure and slower presentations',
      'Green pumpkin color plastic worm catches WA largemouth year-round in most conditions',
    ],
  },
  {
    speciesId: 'smallmouth',
    whereToFind: [
      'Rocky points and gravel bars in rivers — smallmouth love current and rocky substrate',
      'Rocky lake shorelines with boulders and cobble in 3–15 feet of water',
      'Columbia River backwaters and pools are home to world-class smallmouth populations',
      'Current seams and eddy lines in large rivers where fish ambush drifting prey',
    ],
    bestBait: [
      { name: 'Crayfish imitation (tube jig, swimbait)', when: 'Top smallmouth bait in WA — match the brown/orange crayfish color' },
      { name: 'Tube jig (3–4 inch)', when: 'Dragged along rocky bottom; the most consistent Columbia River technique' },
      { name: 'Drop shot (finesse worm)', when: 'Current seams and mid-depth structure; very effective in clear water' },
      { name: 'Small crankbait (squarebill or shad)', when: 'Covering water quickly along rocky shorelines' },
    ],
    technique: [
      'Bounce tube jigs and crayfish imitations along rocky bottom — slow drag and occasional hop',
      'Drop shot in current seams with finesse worm; use enough weight to stay near bottom',
      'Swim tube jigs through current pockets and behind boulders at current speed',
      'In rivers, position upstream from structure and let lures drift naturally into holding positions',
    ],
    bestTime: 'Summer peak June–August; river fish bite best early morning before the sun hits the water; post-spawn (June–July) fish are aggressive.',
    proTips: [
      'Columbia River has some of the best smallmouth fishing in the western US — 5+ pound fish are common',
      'Crayfish are the primary forage: brown/orange tube jigs will consistently out-fish brighter colors in clear water',
      'Wade rocky river bars with care — polarized glasses help you spot fish before spooking them',
    ],
  },
  {
    speciesId: 'muskie',
    whereToFind: [
      'Weed beds in 8–20 feet of water during summer — tiger muskie are ambush predators',
      'Rocky points and transition areas between flats and deep water',
      'Long Lake, Rowland Lake, and a handful of other select WA lakes with stocked populations',
      'Near the thermocline in summer; shallower in spring and fall',
    ],
    bestBait: [
      { name: 'Large glide bait or jerkbait (6–10 inch)', when: 'Top trophy muskie presentation; work with long pauses' },
      { name: 'Bucktail spinner (8–10 inch)', when: 'Covering water fast; use figure-8 at boatside to trigger follows' },
      { name: 'Large topwater bait (Whopper Plopper)', when: 'Low light conditions and summer warm water' },
      { name: 'Large swimbait (5–8 oz)', when: 'Slow rolling through weed edges and deep structure' },
    ],
    technique: [
      'Always finish your retrieve with a figure-8 at the rod tip — many muskie follow and strike at boatside',
      'Long casts, big baits, and patience — muskie are called the "fish of 10,000 casts"',
      'Work each spot thoroughly before moving; muskie are territorial and may take multiple presentations to trigger',
      'Heavy gear is mandatory: 80–100 lb fluorocarbon leader and beefy rod/reel combo',
    ],
    bestTime: 'Fall (September–November) is prime time for trophy fish; early morning and dusk in summer.',
    proTips: [
      'WA tiger muskie are a stocked hybrid (tiger × northern pike cross) — check with WDFW for current stocking lakes',
      'Use steel leaders — muskie have razor-sharp teeth that will sever monofilament instantly',
      'Tiger muskie are rare and hard to catch — even one bite in a day is considered excellent fishing',
    ],
  },
  {
    speciesId: 'pike',
    whereToFind: [
      'Shallow weedy bays and marshy areas in eastern WA lakes',
      'Pend Oreille River, Lake Roosevelt, and Lake Spokane have established populations',
      'Submerged vegetation edges and emergent reeds in 2–8 feet of water',
      'Note: Northern pike are invasive in WA — check regulations and remove fish if in restricted waters',
    ],
    bestBait: [
      { name: 'Large spoon (Dardevle)', when: 'Classic northern pike lure; cast along weed edges and retrieve steadily' },
      { name: 'Large inline spinner (Mepps #5–6)', when: 'Covering water; pike hit spinners aggressively' },
      { name: 'Large jerkbait / glide bait', when: 'Trophy fish; work with long pauses and erratic twitches' },
      { name: 'Live sucker or large minnow', when: 'Bank fishing with a float; pike are voracious live bait takers' },
    ],
    technique: [
      'Cast along the outer edge of weed beds and retrieve steadily just above the tops',
      'Jerkbait: twitch sharply, pause 2–3 seconds, twitch again — pike often strike on the pause',
      'Figure-8 at the rod tip like muskie fishing — pike frequently follow and commit at boatside',
      'Steel leader is mandatory — pike teeth will cut any non-wire leader instantly',
    ],
    bestTime: 'Spring (April–May) in shallow bays as water warms; fall as pike feed aggressively before winter.',
    proTips: [
      'Northern pike are invasive in most WA waters — WDFW strongly encourages removing all caught fish',
      'In approved waters, no bag limit may apply to pike; check current regulations carefully',
      'Pike teeth are extremely sharp — use long-nosed pliers and a jaw spreader for safe hook removal',
    ],
  },
  {
    speciesId: 'catfish',
    whereToFind: [
      'Warm, slow-moving rivers and deep reservoirs in eastern Washington',
      'Slack water areas, deep holes, and undercut banks in the Snake, Columbia, and Yakima rivers',
      'Near structure like submerged rocks, logs, and bridge pilings on the bottom',
      'McNary Reservoir and lower Snake River have excellent catfish populations',
    ],
    bestBait: [
      { name: 'Night crawlers', when: 'Standard catfish bait; works day and night in all conditions' },
      { name: 'Chicken liver / shad guts', when: 'Strong scent attractant for larger fish; especially effective at night' },
      { name: 'Stink bait / dough bait', when: 'Treble hook bait for bank fishing; commercial formulas work well' },
      { name: 'Cut shad or sucker', when: 'Trophy channel cats; cut bait releases scent trail that attracts fish from distance' },
    ],
    technique: [
      'Bottom fishing with a slip sinker rig — let the fish run before setting the hook',
      'Fish after dark for the largest channel catfish; they feed most actively at night',
      'Cast to deeper holes and wait; catfish are not chasers — they find your bait by smell',
      'Multiple rods spread across different depths and locations can help locate fish',
    ],
    bestTime: 'Summer nights (June–September) when water is warm; right after sunset through midnight.',
    proTips: [
      'Channel catfish are the only catfish species in most WA waters — very abundant in eastern WA rivers',
      'Stout tackle is a must for large channel cats which commonly reach 5–15 pounds in WA',
      'For the best bite, find a deep hole with current edges adjacent to it — catfish use current seams to find food',
    ],
  },
  {
    speciesId: 'walleye',
    whereToFind: [
      'Sandy or rocky bottom areas in rivers with current breaks nearby',
      'River mouths where rivers enter reservoirs — transition zones are walleye hotspots',
      'Lake Roosevelt and Banks Lake are the premier WA walleye destinations',
      'Depth transitions along reservoir edges, especially at 15–30 foot contours',
    ],
    bestBait: [
      { name: 'Jig (1/4–1/2 oz) tipped with minnow or Gulp', when: 'Year-round producer; vertical jigging and casting in current' },
      { name: 'Bottom bouncer with crawler harness', when: 'Summer trolling along depth breaks; very productive' },
      { name: 'Crankbait trolled at precise depth', when: 'Covers water to locate fish during low-activity periods' },
      { name: 'Live minnow on lindy rig', when: 'Slow methodical fishing along bottom structure' },
    ],
    technique: [
      'Vertical jig in current seams — let the jig hit bottom, raise 6 inches, let fall back; repeat',
      'Troll bottom bouncers with spinner harness along depth breaks at 1–1.5 mph',
      'Night fish during summer: walleye move to shallow flats in low light to ambush prey',
      'In rivers, position just downstream from current breaks and obstacles that funnel baitfish',
    ],
    bestTime: 'Low-light conditions — dawn, dusk, night, and overcast days; spring (May–June) in shallows after ice-out.',
    proTips: [
      'Walleye have light-sensitive eyes and move to shallow water in low light to feed — night fishing is often the best strategy',
      'Match jig color to water clarity: chartreuse/orange in stained water, white/natural in clear water',
      'Lake Roosevelt has a 100+ mile walleye fishery; bring a boat and explore the upper reservoir near the Canadian border',
    ],
  },
  {
    speciesId: 'perch',
    whereToFind: [
      'Open water suspended over weedy flats in 10–30 feet in summer',
      'Rocky structure and weed beds in lakes; perch school by size so find the right depth',
      'Lake Washington, Lake Sammamish, Moses Lake, and Potholes Reservoir are top WA perch waters',
      'Drop-offs adjacent to weedy shallows where perch forage for invertebrates',
    ],
    bestBait: [
      { name: 'Small jig (1/16–1/8 oz) tipped with worm', when: 'Vertical jigging the most effective year-round technique' },
      { name: 'Small minnow (1–2 inch)', when: 'Live minnows on a small hook are deadly; perch are voracious feeders' },
      { name: 'Night crawler piece', when: 'Simple drift or float rig; works for all sizes' },
      { name: 'Small curly tail grub (2 inch)', when: 'Light jig combo; effective searching lure for locating schools' },
    ],
    technique: [
      'Use a fish finder to locate schools; perch suspend at a specific depth — match it exactly',
      'Vertical jigging from an anchored boat is most effective; small, subtle movements work best',
      'Once you catch one perch, drop back to the exact same depth — school will still be there',
      'Use ultralight gear (4–6 lb line) for maximum sensitivity and fun',
    ],
    bestTime: 'Summer peak when fish are active; early morning in shallower water; ice fishing through winter on eastern WA lakes.',
    proTips: [
      'Yellow perch are schooling fish — when you find one, you\'ve found hundreds; capitalize quickly before the school moves',
      'No size limit on most WA waters and generous daily limits — great for fish fry meals',
      'Color matters: chartreuse jigs often outperform other colors but carry several options and match what\'s working',
    ],
  },
  {
    speciesId: 'crappie',
    whereToFind: [
      'Brush piles and submerged timber in lowland lakes — crappie love woody cover',
      'Dock pilings and bridge supports in 6–15 feet of water',
      'Flooded timber in reservoirs; Columbia River backwaters and East WA lakes',
      'Weed edges where crappie ambush tiny baitfish',
    ],
    bestBait: [
      { name: 'Small tube jig (1/16 oz, 2 inch)', when: 'Best all-around crappie lure; white, pink, or chartreuse' },
      { name: 'Small plastic grub on light jig head', when: 'Vertical jigging under docks and brush' },
      { name: 'Small minnow (1 inch)', when: 'Live bait under a small float is extremely effective' },
      { name: 'Small inline spinner (size 0–1)', when: 'Covering water to locate schools' },
    ],
    technique: [
      'Vertical jigging under brush piles and docks — lower jig to bottom, lift 6 inches, pause; repeat',
      'Spider rigging (multiple rods at various depths) from a boat to cover the water column',
      'Cast small jigs to the base of dock posts and let sink; retrieve slowly just above bottom',
      'Night fishing under lights in summer — lights attract bugs, bugs attract minnows, crappie follow',
    ],
    bestTime: 'Spring (April–June) spawning period when fish move to shallow water and can be sight-fished on beds.',
    proTips: [
      'Crappie are very prolific and have liberal limits in most WA waters — an excellent fish fry target',
      'In spring, look for crappie in 2–6 feet near dock pilings and emergent reeds — they spawn in shallower water than most people think',
      'Keep moving until you find a school; crappie are structure-oriented but relocate frequently',
    ],
  },
  {
    speciesId: 'bluegill',
    whereToFind: [
      'Shallow weedy bays in 2–6 feet — bluegill are consistent shallow-water residents',
      'Dock areas and boat ramps where overhead cover exists',
      'Lower Columbia River area and eastern WA lowland lakes',
      'Warm shallow inlets and arms of lakes that heat up quickly in spring',
    ],
    bestBait: [
      { name: 'Worm piece on small hook', when: 'Simplest and most consistent bluegill bait; works for beginners and all ages' },
      { name: 'Cricket / grasshopper', when: 'Natural surface bait; cast to feeding fish near the top' },
      { name: 'Small dry fly / wet fly (size 10–14)', when: 'Excellent fly rod species; bluegill love flies near the surface' },
      { name: 'Tiny plastic curly tail grub', when: 'Jigging under a float; covers the column when fish aren\'t on surface' },
    ],
    technique: [
      'Float fishing with a worm: set a small bobber 12–18 inches up; bluegill are rarely deeper than 5 feet',
      'Fly fishing with a 4–5 wt rod and small wet flies or surface poppers is incredible sport',
      'Cast near lily pads and dock edges; let bait sink slowly through the shadow zone',
      'Light tackle (4 lb line) maximizes the fight and sensitivity',
    ],
    bestTime: 'Spring and early summer (May–July) during and after the spawn; mid-day in shallow warm water.',
    proTips: [
      'Bluegill are perfect for introducing kids to fishing — they bite eagerly and are easy to find in most WA lowland lakes',
      'No bag limit on most WA waters; liberal rules since bluegill are prolific reproducers',
      'WA bluegill are not as large as their midwest counterparts but still very fun on ultralight gear',
    ],
  },
  {
    speciesId: 'burbot',
    whereToFind: [
      'Deep cold lakes in northeastern Washington — Lake Roosevelt and Rufus Woods Reservoir',
      'Near the bottom in 50–150 feet during summer; shallower (10–30 ft) in winter',
      'Rocky structure and submerged points in cold, deep eastern WA reservoirs',
      'Pend Oreille River above and below the Idaho border',
    ],
    bestBait: [
      { name: 'Large jig (1–2 oz) tipped with fish', when: 'Vertical jigging is most effective in winter when fish are active' },
      { name: 'Cut sucker / whitefish', when: 'Burbot are attracted to scent; cut bait releases oils they can detect' },
      { name: 'Night crawler on bottom rig', when: 'Simple bottom fishing from a boat over deep structure' },
      { name: 'Large tube jig', when: 'Winter jigging through the ice if lake allows; aggressive action triggers strikes' },
    ],
    technique: [
      'Winter is the prime season — burbot spawn under the ice and are highly catchable in January–February',
      'Vertical jigging at night in winter: aggressive lift-drop action near bottom',
      'Bottom fishing with scented bait in deep water (50–120 feet) using heavy weights',
      'Ice fishing: drill holes and jig aggressively; burbot will travel to the hole',
    ],
    bestTime: 'Winter peak January–February during spawning; active at night and in cold dark conditions.',
    proTips: [
      'Burbot are the only freshwater cod species — their flesh is incredibly flavorful and rivals saltwater cod',
      'They\'re nocturnal and cold-water adapted; the best fishing is often on the coldest, darkest winter nights',
      'Liver from burbot is considered a delicacy — if you keep fish, save the liver',
    ],
  },
  {
    speciesId: 'carp',
    whereToFind: [
      'Warm, shallow mud-bottomed lakes and slow rivers throughout western and eastern WA',
      'Columbia River backwaters, Yakima River lower sections, and lowland ponds',
      'Shallow flats where carp root in the mud making "mudballs" visible on the surface',
      'Near the outlet areas of warm irrigation canals flowing into lakes',
    ],
    bestBait: [
      { name: 'Boilies (fishmeal or fruit flavors)', when: 'European-style specimen fishing; soak in attractant then use hair rig' },
      { name: 'Sweet corn (whole kernel)', when: 'Top simple carp bait; use on a small hook with light tackle' },
      { name: 'Bread crust / dough ball', when: 'Surface fishing for visible feeding carp' },
      { name: 'Night crawlers', when: 'Simple and effective; drifted near bottom in current' },
    ],
    technique: [
      'Hair rig fishing: attach bait just behind the hook on a hair rig so carp inhale the bait naturally',
      'Sight fishing: spot tailing carp on flats in clear shallow water and present bait directly to them',
      'Pre-bait an area with corn or pellets to attract and hold carp before fishing',
      'Fly fishing with crayfish imitation — crawl slowly along muddy bottom toward feeding fish',
    ],
    bestTime: 'Late spring through fall; warm afternoons on sunny days when carp are most active in the shallows.',
    proTips: [
      'Carp are increasingly popular as a sport fish — they fight incredibly hard, routinely reaching 10–30 lbs in WA',
      'Sight fishing for carp on shallow flats with fly gear is similar to permit fishing in the tropics — thrilling',
      'Carp are not considered good table fare by most WA anglers but catch-and-release is growing in popularity',
    ],
  },
  // ─── MARINE ──────────────────────────────────────────────────────────────────
  {
    speciesId: 'sturgeon',
    whereToFind: [
      'Deep holes on the Columbia and Snake Rivers — 30–80 feet at the base of rocky ledges',
      'Below dams where current concentrates food and fish stage',
      'Tidal sections near the Columbia bar where food concentrates',
      'Sandy or gravelly bottom adjacent to strong current seams',
    ],
    bestBait: [
      { name: 'Sand shrimp (whole)', when: 'The #1 WA sturgeon bait; large shrimp on a sturgeon-sized circle hook' },
      { name: 'Lamprey pieces (frozen)', when: 'Incredibly effective scent bait; cut into 3–4 inch sections' },
      { name: 'Smelt or eulachon (whole)', when: 'Spring run bait fish; fish whole on a large circle hook' },
      { name: 'Night crawlers (multiple)', when: 'Simple drifted bait below dams; bunch several crawlers together' },
    ],
    technique: [
      'Heavy bottom fishing with a 4–8 oz pyramid sinker; use 50+ lb braid and a circle hook — no hook set needed, reel tight',
      'Anchor above a deep hole and let the scent trail drift downstream to attract fish',
      'Use bait elastic (stretchy thread) to keep shrimp on the hook through the current',
      'Let the rod tip pull down and reel — fighting a sturgeon is about steady pressure, not speed',
    ],
    bestTime: 'Spring (April–May) and fall (October–November) are peak for legal-sized fish; check season carefully — sturgeon is heavily regulated.',
    proTips: [
      'Most WA sturgeon fishing is catch-and-release — the slot size is very narrow (between 38–54 inches on Columbia); measure carefully',
      'Sturgeon can live 100+ years; handle gently, keep in water, support the belly, and release quickly',
      'Guided trips are highly recommended for first-time sturgeon anglers — the Columbia near Kennewick and Portland area is premier',
    ],
  },
  {
    speciesId: 'crab',
    whereToFind: [
      'Sandy and muddy bottom in 20–80 feet throughout Puget Sound, Hood Canal, and the Pacific coast',
      'Grays Harbor and Willapa Bay in Southwest WA for coastal Dungeness populations',
      'Move with tides — concentrate in channels and at depth transitions',
      'Eelgrass beds and rocky bottom transitions are productive crabbing areas',
    ],
    bestBait: [
      { name: 'Chicken carcass or turkey legs', when: 'Classic, inexpensive, and highly effective crab attractant' },
      { name: 'Commercial crab bait jar (anise-scented)', when: 'Long-lasting in the pot; replace every 4–6 hours' },
      { name: 'Fish carcasses or shrimp heads', when: 'Strong scent from oily fish attracts crab from distance' },
      { name: 'Bait bag with herring pieces', when: 'Mesh bait bag inside the pot; crabs can smell but not eat it' },
    ],
    technique: [
      'Drop crab pots to bottom and mark with a buoy; retrieve and check every 1–2 hours',
      'Ring nets from a dock work well at night — drop, wait 20 minutes, haul up quickly',
      'Check current tables: crab feed most actively during tidal movement, especially slack-to-flowing transitions',
      'Measure every crab before keeping — 6.25 inches across the back shell is the legal minimum',
    ],
    bestTime: 'Late summer through winter (July–January) is generally peak; incoming tide concentrates crab in accessible areas.',
    proTips: [
      'Puget Sound and coast Dungeness seasons are different and vary by year — always check WDFW season opener before purchasing gear',
      'Female crabs must be released — identify by the wide, rounded apron on the underside vs. the narrow apron on males',
      'Bring a tape measure and cooler — large hauls are common when conditions are right and seasons are open',
    ],
  },
  {
    speciesId: 'halibut',
    whereToFind: [
      'Sandy and muddy bottom in 100–400 feet in the Strait of Juan de Fuca and north Sound',
      'Neah Bay area is the top WA halibut port — accessible to offshore grounds',
      'Migration routes along the shelf edge — halibut move with the season',
      'Look for depth transitions from 150 to 300 feet where halibut stage to feed',
    ],
    bestBait: [
      { name: 'Large whole herring (frozen/fresh)', when: 'Standard drift bait on spreader bar rig; very effective' },
      { name: 'Octopus chunks (6–8 oz)', when: 'Excellent scent bait in deeper water; halibut smell it from far away' },
      { name: 'Large circle hook on spreader bar', when: 'Standard rig with 16–32 oz sinker; keep bait just off bottom' },
      { name: 'Large jigging spoon (8–16 oz)', when: 'Tip with bait; jig 2–3 feet off bottom aggressively' },
    ],
    technique: [
      'Bottom drift fishing with heavy spreader bar rig; keep bait within 1–2 feet of the bottom',
      'Jig with a large lead-head tipped with herring or squid — raise 3–4 feet and let flutter back down',
      'Drift with the current rather than anchoring; cover more ground to locate feeding fish',
      'When you feel a bite, let the circle hook do the work — just start reeling steadily',
    ],
    bestTime: 'May–August when the IPHC quota season is open; tide changes trigger feeding; morning bite usually best.',
    proTips: [
      'WA halibut season is short (often weeks) and quota-limited — check IPHC and WDFW for exact open dates before planning',
      'Circle hooks dramatically improve catch-and-release survival — use them even if keeping fish',
      'Halibut lay flat on the bottom — set your hook straight up with a vertical rod angle',
    ],
  },
  {
    speciesId: 'lingcod',
    whereToFind: [
      'Rocky reefs and underwater structure in 60–300 feet in the Strait and San Juans',
      'Kelp beds and reef edges where strong current flows',
      'Around San Juan Islands, Sekiu, and Port Angeles near strong tidal currents',
      'Underwater pinnacles and humps that concentrate baitfish and lingcod below them',
    ],
    bestBait: [
      { name: 'Large white/chartreuse jig (4–8 oz)', when: 'Vertical jigging near structure is the primary technique' },
      { name: 'Large swimbait (6–10 inch)', when: 'Work aggressively near bottom; ling will attack large swimbaits' },
      { name: 'Whole large herring (rigged)', when: 'Bottom bait when jigging is slow; ling often take stationary bait' },
      { name: 'Live rockfish or greenling', when: 'Most effective bait of all — use if incidentally caught' },
    ],
    technique: [
      'Drop jig to bottom, raise 2–4 feet, work aggressively — snap, pause, snap; lingcod need triggering',
      'Keep rod tip up when a fish takes — they immediately head for structure and will wrap your line',
      'Use heavy gear (65+ lb braid, heavy rod) — ling are strong and structure-oriented',
      'When you feel the "grab" of a ling biting a hooked rockfish — pause and let the ling commit before gaffing',
    ],
    bestTime: 'Winter and spring peak (November–March); kelp beds are best; low slack tide when current eases.',
    proTips: [
      'Ling will grab smaller rockfish you\'ve hooked and hold on — lower a treble hook next to a hooked rockfish to snag the ling',
      'One legal lingcod per day in most WA Puget Sound areas — make it count',
      'Ling can be caught incidentally while bottomfishing for other species — always have heavy enough gear',
    ],
  },
  {
    speciesId: 'rockfish',
    whereToFind: [
      'Rocky reefs, underwater pinnacles, and structure in 40–300 feet throughout Puget Sound and the Strait',
      'Kelp beds along shorelines — black rockfish hold near the surface in kelp',
      'Vertical underwater walls and deep reef edges in the San Juan Islands',
      'Puget Sound has excellent black rockfish near kelp beds in 30–60 feet',
    ],
    bestBait: [
      { name: 'Jig (2–4 oz lead-head with grub)', when: 'Vertical jigging near structure; most consistent technique' },
      { name: 'Small swimbait (3–5 inch)', when: 'Excellent in kelp for black rockfish; retrieve near canopy' },
      { name: 'Dropper loop with cut herring (2–3 hooks)', when: 'Multiple baited hooks cover the column; great for mixed bottomfish' },
      { name: 'Shrimp fly (size 1–2) on dropper loop', when: 'Quillback and copper rockfish near deeper structure' },
    ],
    technique: [
      'Drop to near bottom near structure and work the jig with short lifts; vary depth until you locate fish',
      'For surface kelp fish: cast into the kelp canopy and retrieve through the edge at medium speed',
      'Dropper loop rigs: lower to bottom, raise 6 inches, let sit — bites are often subtle',
      'Note the exact depth of your first fish on the sonar and return to it systematically',
    ],
    bestTime: 'Year-round but spring and summer are best; tide changes are key as fish feed heavily in current.',
    proTips: [
      'Rockfish are extremely susceptible to barotrauma when brought up from deep water — use a descender device for all released fish',
      'Many Puget Sound rockfish areas have reduced or no-retention rules — always check the current year\'s regulations before fishing',
      'Rockfish can live 100–200 years — handle them with extreme care and release gently using a descender',
    ],
  },
  {
    speciesId: 'cabezon',
    whereToFind: [
      'Rocky nearshore areas in 10–80 feet, especially areas with mixed rock and sand',
      'Kelp beds and boulder fields along Puget Sound and the Strait of Juan de Fuca',
      'Often share habitat with lingcod and black rockfish near structure',
      'San Juan Islands and the northern Strait are top WA cabezon areas',
    ],
    bestBait: [
      { name: 'Crab pieces (fresh)', when: 'Cabezon love crustaceans; fresh dungeness pieces are top bait' },
      { name: 'Shrimp or prawn', when: 'Natural forage; bottom-bounced near structure' },
      { name: 'Small jig (1–2 oz) in pink/white', when: 'Bounced along bottom near rocky structure' },
      { name: 'Cut herring or squid', when: 'On a bottom rig near rocky areas' },
    ],
    technique: [
      'Bottom fish near rocky structure — cabezon rarely leave their ambush territory',
      'Bounce bait slowly along the bottom surface; cabezon will grab and hold, then let go if they feel resistance',
      'Let fish take the bait fully before setting; delay hook set 3–5 seconds',
      'Use heavy enough gear to pull fish away from structure immediately after hooking',
    ],
    bestTime: 'Fall and winter (October–March) are peak feeding times; spawning males guard nests in rocky areas.',
    proTips: [
      'Cabezon eggs (roe) are toxic — do not eat them under any circumstances; the flesh is excellent, however',
      'Check the daily limit carefully — cabezon regulations in Puget Sound are often restrictive',
      'Cabezon are strong short-distance fighters; once hooked they head for rock crevices immediately',
    ],
  },
  {
    speciesId: 'greenling',
    whereToFind: [
      'Kelp beds and rocky reefs in 5–60 feet; very accessible from shore',
      'Eelgrass beds and mixed rock/sand habitat throughout Puget Sound',
      'Shallow rocky shorelines accessible from the beach',
      'Around dock pilings and jetty rocks in harbors and marinas',
    ],
    bestBait: [
      { name: 'Small jig (1/2–1 oz) in white/chartreuse', when: 'Excellent near kelp; cast into beds and retrieve slowly' },
      { name: 'Small spinner (1/4 oz)', when: 'Versatile searching lure along rocky shorelines' },
      { name: 'Shrimp pieces or prawn', when: 'Natural forage; float rig or light bottom rig near kelp' },
      { name: 'Pile worm / sandworm', when: 'Classic kelp greenling bait; bottom-fished near rocky structure' },
    ],
    technique: [
      'Cast small jigs and spinners into kelp bed edges and retrieve through the canopy',
      'Fish from kayak or shore along kelp-lined rocky shorelines for consistent action',
      'Slow retrieve near the bottom adjacent to rocky structure',
      'Light to medium gear (8–12 lb) provides the best sport with this willing species',
    ],
    bestTime: 'Year-round but spring and summer are most productive; mid-day on sunny days when fish are visible and active.',
    proTips: [
      'Kelp greenling are commonly encountered while fishing for other rockfish species',
      'The ling greenling (larger relative) reaches several pounds and fights hard on light tackle',
      'Check bag limits — in some areas combined bag limits with other rockfish apply',
    ],
  },
  {
    speciesId: 'cod',
    whereToFind: [
      'Deeper areas of Puget Sound in 100–300 feet; near the bottom over soft substrate',
      'Hood Canal in deeper sections has consistent cod populations',
      'Channels and troughs between the main Sound and tributary inlets',
      'Transition areas from soft mud to gravel bottom at depth',
    ],
    bestBait: [
      { name: 'Jigging spoon (3–6 oz) with herring', when: 'Vertical jigging near bottom; tip with bait for scent' },
      { name: 'Dropper loop with herring strip (2 hooks)', when: 'Bottom presentation covering two depths simultaneously' },
      { name: 'Whole herring on bottom rig', when: 'Stationary bottom fishing; cod will come to bait' },
      { name: 'Large white jig (3–4 oz)', when: 'Aggressive jigging to trigger reaction strikes' },
    ],
    technique: [
      'Bottom fish with bait or jig in the deepest accessible water — Pacific cod are cold-water, deep-dwelling fish',
      'Vertical jigging: drop to bottom, raise 2 feet, jig aggressively, pause 5–10 seconds; repeat',
      'Use downriggers or heavy weights (4–8 oz) to get bait to depth in current',
      'Multiple hooks increase catch rate; use a dropper loop rig with 2–3 baited hooks',
    ],
    bestTime: 'Winter (November–March) is prime season when cod move into Puget Sound in greater numbers.',
    proTips: [
      'Pacific cod are excellent table fish — very similar to Atlantic cod in flavor and texture',
      'They\'re less commonly targeted in WA than other bottomfish but are worth seeking in deep water',
      'Cold water brings cod into shallower ranges; water temperature below 50°F is ideal',
    ],
  },
  {
    speciesId: 'sablefish',
    whereToFind: [
      'Deep offshore water in 600–3,000 feet — primarily an offshore commercial and charter target',
      'Submarine canyons and deep soft-bottom areas off the WA coast',
      'Occasionally caught in 300–500 feet during nearshore bottom fishing',
      'Neah Bay and Westport charter boats make sablefish trips in season',
    ],
    bestBait: [
      { name: 'Whole squid or herring on deep rig', when: 'Most commercial and charter fishing uses large baited hooks dropped to depth' },
      { name: 'Large heavy jig (8–16 oz)', when: 'Deep vertical jigging for sport catches' },
      { name: 'Any bait — sablefish are not selective', when: 'They eat almost anything at depth; the challenge is getting bait to them' },
    ],
    technique: [
      'Deep-water bottom fishing with very heavy weights to reach 1,000+ feet',
      'Electric reels are standard equipment for sablefish fishing given extreme depths',
      'Charter boats from Westport or Neah Bay offer the most realistic access for sport anglers',
      'When one fish comes up, the whole school is usually at that depth — jig up and down to maximize catches',
    ],
    bestTime: 'May through August when sablefish migrate to accessible depths; summer charter trips are most productive.',
    proTips: [
      'Sablefish (black cod) has the most omega-3 fatty acids of any fish in the Pacific — world-class table fare',
      'Their buttery, rich flesh is prized by top restaurants; a sablefish charter trip is a worthwhile investment',
      'Check charter availability from Westport or Neah Bay — most sport anglers access sablefish through guided trips',
    ],
  },
  {
    speciesId: 'surfperch',
    whereToFind: [
      'Sandy surf beaches along the WA coast from the Columbia River north to Cape Flattery',
      'Beach areas near rocky jetties, river mouths, and estuaries',
      'In the surfzone — these fish actively forage in the breaking waves',
      'Puget Sound beaches also have redtail surfperch in protected locations',
    ],
    bestBait: [
      { name: 'Sand crab (mole crab)', when: 'The top surfperch bait on WA ocean beaches; dig them in the swash zone' },
      { name: 'Pile worm / sand worm', when: 'Excellent in all conditions; cut into 1 inch pieces on small hook' },
      { name: 'Small grub (2 inch pink/white)', when: 'Artificial option that works well in the surf zone' },
      { name: 'Shrimp pieces', when: 'Widely available bait that surfperch aggressively take' },
    ],
    technique: [
      'Cast into the surfzone — the third breaker line is often where fish forage in the foam',
      'Use a 2-hook surf rig with sinker; cast with heavy monofilament (20–30 lb) for casting distance',
      'Wade in the surf for better access; surfperch are often in water you can walk to',
      'Work different spots along the beach — fish stack in specific areas based on wave action',
    ],
    bestTime: 'Spring and early summer (May–July) is peak for the best fishing along ocean beaches; incoming tide is most productive.',
    proTips: [
      'Surfperch are one of the most accessible WA saltwater fish — no boat needed, just wade and cast',
      'No size limit and generous daily limits on most WA ocean beaches — great family fishing',
      'The best beach access points are near Ocean Shores, Westport, and Long Beach Peninsula',
    ],
  },
  {
    speciesId: 'flounder',
    whereToFind: [
      'Sandy and muddy bottom in shallow bays, estuaries, and tidal flats',
      'Commencement Bay, Budd Inlet, and Bellingham Bay have consistent flounder populations',
      'Near eelgrass beds where flatfish wait to ambush prey',
      'Tidal channels adjacent to sandy flats — flounder move in on tidal flooding',
    ],
    bestBait: [
      { name: 'Sand worm / pile worm', when: 'Best all-around flounder bait; bottom rig in 5–30 feet' },
      { name: 'Small whole herring', when: 'Flounder eat baitfish; small herring on a hook near bottom' },
      { name: 'Shrimp pieces', when: 'Natural forage; bottom rigged with light sinker' },
      { name: 'Small jig (1/2–1 oz) with trailer', when: 'Can be jigged off bottom slowly through sandy areas' },
    ],
    technique: [
      'Bottom fishing with a light sinker — flounder are near the surface of the sand, not deep',
      'Drag bait slowly across the bottom; flounder will pounce on moving prey',
      'Use very light sinkers and minimal weight — flounder are in shallow water where heavy rigs are unnecessary',
      'Fish on an incoming tide as flounder move onto flats to feed on worms and shrimp',
    ],
    bestTime: 'Spring and summer (April–August) are most productive; incoming tide on sandy flats and estuaries.',
    proTips: [
      'WA flounder and sole are multiple species — English sole, sand sole, and starry flounder are most common',
      'Flounder are excellent table fish despite their humble reputation — very mild and versatile',
      'No size limit and generous bag limits in most areas make flounder a great year-round option',
    ],
  },
  {
    speciesId: 'razorclam',
    whereToFind: [
      'Sandy ocean beaches on the WA coast: Ocean Shores, Mocrocks, Copalis, Twin Harbors, and Long Beach',
      'Found in the intertidal zone — dig from the high-tide line down into the water',
      'Areas with firm sand and moderate wave action tend to hold more clams',
      'Look for the characteristic "dimple" or show in the sand where the clam is near the surface',
    ],
    bestBait: [
      { name: 'Not applicable — digging species', when: 'Razor clams are dug with a clam gun or shovel, not caught on a hook' },
    ],
    technique: [
      'Use a clam gun (tube) over the show and push down firmly, then pull straight up with a twisting motion',
      'Shovel method: dig 6 inches seaward of the show and intercept the clam before it digs too deep',
      'Clams can dig 6–12 inches per minute — move fast after spotting a show',
      'Dig in the lower intertidal zone during the lowest tides for most clams and largest size',
    ],
    bestTime: 'Fall through early spring (October–March) during evening or nighttime low tides on WDFW-approved beaches.',
    proTips: [
      'WDFW issues specific dig openings for each beach — check the website before going as seasons are not continuous',
      'A limit is 15 clams per person; they must be kept regardless of size (first 15 you dig are your limit)',
      'Bring a headlamp and check tide tables — the best low tides for digging often occur after dark',
    ],
  },
  {
    speciesId: 'shrimp',
    whereToFind: [
      'Deep water (100–300 feet) throughout Puget Sound and Hood Canal',
      'Hood Canal has excellent spot shrimp populations near deep-water channels',
      'Possession Sound, Port Susan, and South Sound all have spot shrimp seasons',
      'Look for clean sandy/gravelly bottom in deep channels — check WDFW maps for legal areas',
    ],
    bestBait: [
      { name: 'Commercial spot shrimp bait (anise-scented)', when: 'Drops to depth with the trap; oil-based scent disperses through the water column' },
      { name: 'Chicken carcass or oily fish', when: 'DIY trap bait that works well' },
      { name: 'Not applicable — trap fishery', when: 'Spot shrimp are caught in traps, not on hook and line' },
    ],
    technique: [
      'Lower shrimp traps to 100–300 feet on the soft bottom and mark with a buoy',
      'Soak traps for 30–90 minutes before hauling — don\'t leave overnight as traps overfill and stress shrimp',
      'Use multiple traps spread across different depths to find where shrimp are concentrating',
      'Handle gently — shrimp are fragile and losing all their legs is common with rough handling',
    ],
    bestTime: 'May opening day in Puget Sound — the one-day or short season for spot shrimp; check WDFW for exact dates.',
    proTips: [
      'WA spot shrimp season is typically just one day in May for Hood Canal and nearby areas — it\'s a planned event, not casual fishing',
      'Spot shrimp are arguably the best-tasting shrimp in the world — the season is short but completely worth it',
      'Bring a large cooler with ice to keep shrimp fresh; the shell deteriorates quickly at room temperature',
    ],
  },
  {
    speciesId: 'herring',
    whereToFind: [
      'Open water throughout Puget Sound and the Strait of Juan de Fuca',
      'Schools visible on surface as boiling activity or diving birds above them',
      'Near structure and dock areas in winter when herring school inshore',
      'Ferry terminals and marinas in winter often have excellent herring jig fishing',
    ],
    bestBait: [
      { name: 'Multi-hook herring jig (Sabiki rig)', when: 'Vertical jigging through schools is the primary technique' },
      { name: 'Small metal jig or spoon', when: 'Simple jigging when herring are active on the surface' },
      { name: 'Not usually bait fishing — jig species', when: 'Herring are jigged, not caught on bait; they eat plankton' },
    ],
    technique: [
      'Drop a Sabiki rig (6–10 small hooks) through visible schools and slowly jig up and down',
      'Locate schools with polarized glasses looking for surface disturbance or diving birds',
      'At docks in winter, lower a Sabiki below lights at night — herring gather under lights',
      'Catch-and-release or keep for bait; herring caught for bait can be kept in a livewell',
    ],
    bestTime: 'Winter (December–March) when herring school near the surface and inshore; also spring spawn which attracts birds.',
    proTips: [
      'Jigged herring are excellent bait for salmon, halibut, and lingcod — freeze your catch for future use',
      'The herring spawn in Puget Sound (late winter/spring) is an ecological event — watch for diving birds to locate schools',
      'Use minimal hook sizes (size 8–12) on Sabiki rigs for best hook-up rates',
    ],
  },
  {
    speciesId: 'squid',
    whereToFind: [
      'Open water near dock lights throughout Puget Sound — squid are attracted to light',
      'Jetty and pier areas in fall through winter especially around Edmonds, Kingston, and Seattle waterfront',
      'Mid-water column under bright lights on dark nights',
      'Migration-dependent; look for them in harbors from October through February',
    ],
    bestBait: [
      { name: 'Squid jig (size 2–3 with glow)', when: 'Primary and often only lure needed; UV/glow patterns work best' },
      { name: 'Small metal jigging spoon', when: 'Alternative when squid jigs aren\'t available' },
      { name: 'Not bait fishing — jig species', when: 'Squid don\'t eat conventional bait; they\'re caught on jigs' },
    ],
    technique: [
      'Drop a squid jig under dock lights and slowly jig up and down — let it sink to depth, then retrieve slowly',
      'Glow jigs charged with a UV flashlight every few casts work dramatically better in dark conditions',
      'Use a slower, more subtle jigging action than for fish — squid prefer steady movement',
      'When you feel a grab (gentle resistance), don\'t jerk — steadily reel in before the squid releases',
    ],
    bestTime: 'November through January on dark nights when squid are attracted to lights; incoming tide concentrates them near structure.',
    proTips: [
      'Squid jigging off a lit dock on a calm winter night is a uniquely Pacific Northwest tradition — great for families',
      'Bring a bucket with salt water to keep squid fresh while fishing; they deteriorate quickly without water',
      'Squid ink is permanent on clothing — wear old clothes or rain gear when jigging squid from docks',
    ],
  },
  {
    speciesId: 'smelt',
    whereToFind: [
      'WA ocean beaches during summer spawning runs — surf smelt spawn on specific beaches',
      'Beaches near Dungeness Spit, Salt Creek, and beaches on the Strait have known smelt runs',
      'Puget Sound also has populations along sandy beach areas in late summer',
      'Spawning fish congregate very close to shore in the swash zone — sometimes almost on the beach',
    ],
    bestBait: [
      { name: 'Dip net (fine mesh, 24–36 inch)', when: 'Smelt are dip-netted during spawning runs, not caught on hook and line' },
      { name: 'Not applicable — dip net fishery', when: 'Surf smelt are captured by dip netting during their spawning runs on beaches' },
    ],
    technique: [
      'Wade into the surf at knee depth and sweep the dip net through the wave face parallel to shore',
      'Target the foam and wave face area where spawning smelt aggregate',
      'Move down the beach to find the most concentrated spawning activity',
      'Early morning and evening tend to have the most activity',
    ],
    bestTime: 'July–August for surf smelt; spawning occurs during high tides on specific beaches; check WDFW beach listings.',
    proTips: [
      'Surf smelt season and beach locations are specific — check WDFW for current open beaches and dates',
      'Fresh-caught smelt are excellent fried whole; the flavor is delicate and sweet',
      'Eulachon (candlefish) smelt also run the lower Columbia in spring — a different species with different regs',
    ],
  },
  {
    speciesId: 'skate',
    whereToFind: [
      'Soft bottom (sandy, muddy) in 60–300 feet throughout Puget Sound',
      'Often caught incidentally while bottom fishing for other species',
      'Deep channel areas and basins in the central and southern Sound',
      'Common in Hood Canal and the deep channels of Admiralty Inlet',
    ],
    bestBait: [
      { name: 'Sand worm or pile worm', when: 'Bottom-rigged; skates scavenge along the bottom and find worms by scent' },
      { name: 'Cut herring or squid', when: 'Oily cut bait produces a scent trail that attracts skate from distance' },
      { name: 'Night crawler', when: 'Simple effective bottom bait; skates are not selective' },
    ],
    technique: [
      'Bottom fishing with a conventional sinker setup; let bait rest on the bottom',
      'Skates often bite softly — watch for a slow steady pull rather than a strike',
      'Use strong hooks (circle hook 3/0–5/0) — skate cartilage requires a firmly set hook',
      'Land with a net or gloved hand — skates have rough skin and a barbed tail',
    ],
    bestTime: 'Year-round bottom bycatch; no specific seasonal peak as they\'re found at consistent depths year-round.',
    proTips: [
      'Skate "wings" are edible and underrated — the white cartilage-adjacent meat has a mild sweet flavor',
      'Cut the wing sections free immediately after catch for best flavor',
      'Skates are incidental catch rather than a targeted species for most WA anglers',
    ],
  },
]
