export type FishingAccessType =
  | 'bank'
  | 'boat_launch'
  | 'park'
  | 'wdfw_access'
  | 'hatchery'
  | 'public_land'

export type FishingAccessSpot = {
  id: string
  waterId: string
  name: string
  accessType: FishingAccessType
  lat?: number
  lng?: number
  directionsNote: string
  riverFeature: string
  legalityNote: string
  sourceName: string
  sourceUrl?: string
  speciesIds?: string[]
}

const SKYKOMISH_CLOSURE_NOTE =
  'ACCESS ONLY / PLANNING: WDFW emergency rule closes the Skykomish River to all fishing through Oct. 31, 2026 from the mouth to the North/South Fork confluence. Do not fish here while closure is active.'

const DEFAULT_LEGALITY_NOTE =
  'Public access identified from official/credible public access sources. Fishing is legal only when the WDFW section and target species are open; verify current rules before fishing.'

export const FISHING_ACCESS_SPOTS: FishingAccessSpot[] = [
  // Skagit River — public parks / hatchery / WDFW-style access corridors.
  {
    id: 'skagit-howard-miller',
    waterId: 'skagit',
    name: 'Howard Miller Steelhead Park',
    accessType: 'park',
    lat: 48.4886,
    lng: -121.6047,
    directionsNote: 'County park at Rockport with bank access and boat-launch area near the Highway 530 bridge.',
    riverFeature: 'Rockport / upper mainstem bridge water',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Skagit County Parks public park/access',
    sourceUrl: 'https://www.skagitcounty.net/Departments/ParksAndRecreation/parks/howardmiller.htm',
    speciesIds: ['chinook', 'coho', 'steelhead', 'sockeye'],
  },
  {
    id: 'skagit-rasar',
    waterId: 'skagit',
    name: 'Rasar State Park',
    accessType: 'park',
    lat: 48.518,
    lng: -121.905,
    directionsNote: 'State park near Concrete with signed day-use access and river trail frontage.',
    riverFeature: 'Middle Skagit gravel bars / bank water',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Washington State Parks',
    sourceUrl: 'https://parks.wa.gov/find-parks/state-parks/rasar-state-park',
  },
  {
    id: 'skagit-marblemount-hatchery',
    waterId: 'skagit',
    name: 'Marblemount Fish Hatchery area',
    accessType: 'hatchery',
    lat: 48.526,
    lng: -121.436,
    directionsNote: 'Use signed public areas near the hatchery and Cascade River confluence; respect hatchery boundaries.',
    riverFeature: 'Cascade River confluence / hatchery return zone',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'WDFW hatchery/public facility',
    sourceUrl: 'https://wdfw.wa.gov/fishing/locations/hatcheries/marblemount',
  },
  {
    id: 'skagit-edgewater',
    waterId: 'skagit',
    name: 'Edgewater Park — Mount Vernon',
    accessType: 'park',
    lat: 48.421,
    lng: -122.342,
    directionsNote: 'City park on the Skagit in Mount Vernon; bank/path access for lower-river planning.',
    riverFeature: 'Lower Skagit tidal-influence / city bank access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'City of Mount Vernon Parks',
    sourceUrl: 'https://mountvernonwa.gov/',
  },
  {
    id: 'skagit-baker-river-confluence',
    waterId: 'skagit',
    name: 'Baker River confluence public access',
    accessType: 'bank',
    lat: 48.538,
    lng: -121.744,
    directionsNote: 'Use signed public access in Concrete near the Baker River mouth; avoid private parcels.',
    riverFeature: 'Baker River confluence seam',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public access / WDFW regulation landmark',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },

  // Skykomish — shown only as planning while WDFW emergency closure is active.
  {
    id: 'skykomish-reiter',
    waterId: 'skykomish',
    name: 'Reiter Foothills / Reiter Ponds area',
    accessType: 'hatchery',
    lat: 47.836,
    lng: -121.626,
    directionsNote: 'Traditional hatchery-area access near Reiter Road; use only signed public areas.',
    riverFeature: 'Hatchery return zone / upper mainstem',
    legalityNote: SKYKOMISH_CLOSURE_NOTE,
    sourceName: 'WDFW emergency rule / hatchery landmark',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations/emergency-rules/skykomish-river-fishing-will-not-open-until-nov-1-2026-06',
    speciesIds: ['steelhead', 'chinook', 'coho'],
  },
  {
    id: 'skykomish-big-eddy',
    waterId: 'skykomish',
    name: 'Big Eddy public access',
    accessType: 'boat_launch',
    lat: 47.865,
    lng: -121.789,
    directionsNote: 'Public river access near Gold Bar; plan parking and bank use only where signed.',
    riverFeature: 'Pool / run access near Gold Bar',
    legalityNote: SKYKOMISH_CLOSURE_NOTE,
    sourceName: 'Public boat-launch/access listing; WDFW emergency rule controls fishing status',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations/emergency-rules/skykomish-river-fishing-will-not-open-until-nov-1-2026-06',
  },
  {
    id: 'skykomish-al-borlin',
    waterId: 'skykomish',
    name: 'Al Borlin Park',
    accessType: 'park',
    lat: 47.861,
    lng: -121.973,
    directionsNote: 'Monroe city park near the Skykomish/Snoqualmie confluence corridor; stay on public trails.',
    riverFeature: 'Lower Skykomish / confluence-side bank access',
    legalityNote: SKYKOMISH_CLOSURE_NOTE,
    sourceName: 'City of Monroe park; WDFW emergency rule controls fishing status',
    sourceUrl: 'https://www.monroewa.gov/',
  },
  {
    id: 'skykomish-sultan-riverfront',
    waterId: 'skykomish',
    name: 'Sultan riverfront public access',
    accessType: 'park',
    lat: 47.862,
    lng: -121.816,
    directionsNote: 'Use signed public riverfront/park access around Sultan; avoid private lots and rail corridors.',
    riverFeature: 'Sultan-area mainstem runs',
    legalityNote: SKYKOMISH_CLOSURE_NOTE,
    sourceName: 'Public municipal access; WDFW emergency rule controls fishing status',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations/emergency-rules/skykomish-river-fishing-will-not-open-until-nov-1-2026-06',
  },
  {
    id: 'skykomish-highway-2-bridges',
    waterId: 'skykomish',
    name: 'Signed Highway 2 bridge/public pullout access',
    accessType: 'bank',
    lat: 47.837,
    lng: -121.66,
    directionsNote: 'Use only signed public pullouts and legal parking; do not cross private railroad or residential land.',
    riverFeature: 'Bridge pools / tailouts',
    legalityNote: SKYKOMISH_CLOSURE_NOTE,
    sourceName: 'WDFW emergency-rule planning caveat',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations/emergency-rules/skykomish-river-fishing-will-not-open-until-nov-1-2026-06',
  },

  // Yakima River.
  {
    id: 'yakima-umtanum',
    waterId: 'yakima',
    name: 'Umtanum Recreation Area',
    accessType: 'public_land',
    lat: 46.855,
    lng: -120.482,
    directionsNote: 'BLM day-use access off Canyon Road with footbridge/trail access to bank water.',
    riverFeature: 'Yakima Canyon riffles, seams and tailouts',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'BLM Yakima River Canyon recreation site',
    sourceUrl: 'https://www.blm.gov/visit/umtanum-recreation-site',
    speciesIds: ['rainbow', 'brown', 'smallmouth'],
  },
  {
    id: 'yakima-roza',
    waterId: 'yakima',
    name: 'Roza Recreation Site',
    accessType: 'boat_launch',
    lat: 46.789,
    lng: -120.459,
    directionsNote: 'BLM access/launch in Yakima Canyon; popular float take-out/put-in.',
    riverFeature: 'Canyon runs below Roza Dam',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'BLM Yakima River Canyon recreation site',
    sourceUrl: 'https://www.blm.gov/visit/roza-recreation-site',
  },
  {
    id: 'yakima-big-pines',
    waterId: 'yakima',
    name: 'Big Pines Recreation Area',
    accessType: 'public_land',
    lat: 46.875,
    lng: -120.502,
    directionsNote: 'BLM campground/day-use access in Yakima Canyon; use signed public river approaches.',
    riverFeature: 'Canyon bank water and float access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'BLM Yakima River Canyon recreation site',
    sourceUrl: 'https://www.blm.gov/visit/big-pines-recreation-site',
  },
  {
    id: 'yakima-irene-rinehart',
    waterId: 'yakima',
    name: 'Irene Rinehart Riverfront Park',
    accessType: 'park',
    lat: 46.984,
    lng: -120.56,
    directionsNote: 'Ellensburg city park with signed riverfront access; verify local rules and seasonal flows.',
    riverFeature: 'Upper Yakima urban bank access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'City of Ellensburg Parks',
    sourceUrl: 'https://ci.ellensburg.wa.us/',
  },
  {
    id: 'yakima-cle-elum',
    waterId: 'yakima',
    name: 'Cle Elum / South Cle Elum river access',
    accessType: 'park',
    lat: 47.185,
    lng: -120.955,
    directionsNote: 'Use signed public riverfront and trail access around South Cle Elum; avoid private bank parcels.',
    riverFeature: 'Upper Yakima freestone runs',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public municipal/trail access',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },

  // Cowlitz River.
  {
    id: 'cowlitz-blue-creek',
    waterId: 'cowlitz',
    name: 'Blue Creek / Cowlitz Trout Hatchery access',
    accessType: 'hatchery',
    lat: 46.495,
    lng: -122.718,
    directionsNote: 'Well-known public hatchery access near Blue Creek; follow posted boundary and parking signs.',
    riverFeature: 'Hatchery return zone / bank drift water',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'WDFW hatchery/public access landmark',
    sourceUrl: 'https://wdfw.wa.gov/fishing/locations/hatcheries/cowlitz-trout',
    speciesIds: ['steelhead', 'chinook', 'coho'],
  },
  {
    id: 'cowlitz-barrier-dam',
    waterId: 'cowlitz',
    name: 'Barrier Dam / Cowlitz Salmon Hatchery area',
    accessType: 'hatchery',
    lat: 46.521,
    lng: -122.629,
    directionsNote: 'Use signed public access near the salmon hatchery and barrier-dam reach.',
    riverFeature: 'Terminal hatchery reach / deadline-adjacent water',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'WDFW Cowlitz Salmon Hatchery',
    sourceUrl: 'https://wdfw.wa.gov/fishing/locations/hatcheries/cowlitz-salmon',
  },
  {
    id: 'cowlitz-castle-rock',
    waterId: 'cowlitz',
    name: 'Castle Rock boat launch / riverfront',
    accessType: 'boat_launch',
    lat: 46.275,
    lng: -122.907,
    directionsNote: 'Public lower-river launch and bank access near Castle Rock; confirm launch conditions.',
    riverFeature: 'Lower Cowlitz boat and bank access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public municipal boat launch/access',
    sourceUrl: 'https://wdfw.wa.gov/places-to-go/water-access-sites',
  },
  {
    id: 'cowlitz-mission-bar',
    waterId: 'cowlitz',
    name: 'Mission Bar access',
    accessType: 'bank',
    lat: 46.445,
    lng: -122.832,
    directionsNote: 'Use established public access and legal parking only; gravel bars shift with flows.',
    riverFeature: 'Mid-river gravel bar / tailout water',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public access landmark; verify current ownership/signage',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },
  {
    id: 'cowlitz-olequa',
    waterId: 'cowlitz',
    name: 'Olequa / Toledo river access',
    accessType: 'boat_launch',
    lat: 46.439,
    lng: -122.845,
    directionsNote: 'Lower/middle river access around Toledo; use signed launch/park areas.',
    riverFeature: 'Boat access to long lower-river runs',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public boat-launch/access listing',
    sourceUrl: 'https://wdfw.wa.gov/places-to-go/water-access-sites',
  },

  // Snohomish / Snoqualmie / Green / Puyallup / Hoh / Columbia / Snake.
  {
    id: 'snohomish-langus',
    waterId: 'snohomish',
    name: 'Langus Riverfront Park',
    accessType: 'park',
    lat: 47.999,
    lng: -122.187,
    directionsNote: 'Everett riverfront park with public trails/launch access near the lower Snohomish.',
    riverFeature: 'Lower Snohomish tidewater/estuary edge',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'City of Everett Parks',
    sourceUrl: 'https://www.everettwa.gov/',
    speciesIds: ['coho', 'chinook', 'steelhead'],
  },
  {
    id: 'snohomish-lowell',
    waterId: 'snohomish',
    name: 'Lowell Riverfront Trail / Rotary Park',
    accessType: 'park',
    lat: 47.955,
    lng: -122.203,
    directionsNote: 'Public riverfront trail access in Everett/Lowell; fish only where public access and rules allow.',
    riverFeature: 'Lower river bank seams',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'City of Everett public park/trail',
    sourceUrl: 'https://www.everettwa.gov/',
  },
  {
    id: 'snoqualmie-fall-city',
    waterId: 'snoqualmie',
    name: 'Fall City / SR 202 bridge access',
    accessType: 'bank',
    lat: 47.568,
    lng: -121.888,
    directionsNote: 'Use signed public river access near Fall City; avoid private farmland and bridge hazards.',
    riverFeature: 'Bridge pool and lower Snoqualmie runs',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public access landmark; verify signs',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },
  {
    id: 'green-flaming-geyser',
    waterId: 'green',
    name: 'Flaming Geyser State Park',
    accessType: 'park',
    lat: 47.274,
    lng: -122.018,
    directionsNote: 'State park riverfront on the Green River with day-use access and trails.',
    riverFeature: 'Middle Green riffles/runs',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Washington State Parks',
    sourceUrl: 'https://parks.wa.gov/find-parks/state-parks/flaming-geyser-state-park',
    speciesIds: ['coho', 'chinook', 'steelhead'],
  },
  {
    id: 'puyallup-clarks-creek',
    waterId: 'puyallup',
    name: 'Clarks Creek / Puyallup riverfront access',
    accessType: 'park',
    lat: 47.191,
    lng: -122.294,
    directionsNote: 'Use signed city/riverwalk access and legal parking; urban banks include private and closed areas.',
    riverFeature: 'Lower Puyallup urban bank access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'City public riverfront access',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },
  {
    id: 'hoh-oxbow',
    waterId: 'hoh',
    name: 'Hoh Oxbow / DNR campground access',
    accessType: 'public_land',
    lat: 47.811,
    lng: -124.247,
    directionsNote: 'Public campground/river access; Olympic rivers change quickly, so verify bank safety and posted closures.',
    riverFeature: 'Lower Hoh gravel bars and runs',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Washington DNR public recreation access',
    sourceUrl: 'https://www.dnr.wa.gov/',
  },
  {
    id: 'columbia-richland',
    waterId: 'columbia',
    name: 'Columbia Point / Richland waterfront',
    accessType: 'park',
    lat: 46.269,
    lng: -119.267,
    directionsNote: 'Public waterfront access around Columbia Point; check Columbia River zone rules before targeting salmon/steelhead/sturgeon.',
    riverFeature: 'Mid-Columbia shoreline / marina structure',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public municipal waterfront; WDFW Columbia rules apply by zone',
    sourceUrl: 'https://wdfw.wa.gov/fishing/regulations',
  },
  {
    id: 'snake-chief-timothy',
    waterId: 'snake',
    name: 'Chief Timothy Park',
    accessType: 'park',
    lat: 46.424,
    lng: -117.185,
    directionsNote: 'Public park/launch on the Snake River near Clarkston; verify section rules and species seasons.',
    riverFeature: 'Lower Snake reservoir shoreline / launch access',
    legalityNote: DEFAULT_LEGALITY_NOTE,
    sourceName: 'Public park/boat launch access',
    sourceUrl: 'https://wdfw.wa.gov/places-to-go/water-access-sites',
  },
]

export function getAccessSpotsForWater(waterId: string, limit = 5): FishingAccessSpot[] {
  return FISHING_ACCESS_SPOTS.filter(spot => spot.waterId === waterId).slice(0, limit)
}
